name: Build Docker Image
on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
permissions: {}

jobs:
  image_build:
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - context: "naikari-artwork/blender2.79b"
            arch: amd64
            imagename: "naikari-artwork"
            blender: "blender2.79b"
          - context: "naikari-linux-lts"
            arch: amd64
            imagename: "naikari-linux-lts"
          - context: "naikari-linux-latest"
            arch: amd64
            imagename: "naikari-linux-latest"
          - context: "naikari-release"
            arch: amd64
            imagename: "naikari-release"
          - context: "naikari-windows"
            arch: amd64
            imagename: "naikari-windows"
          - context: "naikari-macos"
            arch: amd64
            imagename: "naikari-macos"
          - context: "naikari-macos"
            arch: aarch64
            imagename: "naikari-macos"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Generate image metadata
        id: docker_meta
        if: ${{ matrix.arch != 'aarch64' || matrix.imagename == 'naikari-artwork' }}
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/naikari/${{ matrix.imagename }}
          flavor: |
            latest=${{ inputs.publish }}
      - name: Generate image metadata (aarch64)
        id: docker_meta_aarch64
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/naikari/${{ matrix.imagename }}
          flavor: |
            suffix=-${{ matrix.arch }},onlatest=true
      - name: Generate image metadata (artwork)
        id: docker_meta_artwork
        if: ${{ matrix.imagename == 'naikari-artwork' }}
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/naikari/${{ matrix.imagename }}
          flavor: |
            suffix=-${{ matrix.blender }},onlatest=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        id: docker_build
        if: ${{ matrix.arch != 'aarch64' }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: "${{ matrix.context }}/Dockerfile.${{ matrix.arch }}"
          push: ${{ inputs.publish }}
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Build Image (aarch64)
        id: docker_build_aarch64
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: "${{ matrix.context }}/Dockerfile.${{ matrix.arch }}"
          push: ${{ inputs.publish }}
          tags: ${{ steps.docker_meta_aarch64.outputs.tags }}
